# Generated by Django 2.2 on 2019-04-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_box.Person'),
        ),
        migrations.AlterField(
            model_name='group',
            name='person',
            field=models.ManyToManyField(null=True, to='contact_box.Person'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact_box.Person'),
        ),
    ]
