# Generated by Django 2.2 on 2019-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=32, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.IntegerField(blank=True, verbose_name='flat number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='home_number',
            field=models.IntegerField(verbose_name='home number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=64, verbose_name='street name'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'work')], default=0, verbose_name='email type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=32, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=32, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.IntegerField(verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.IntegerField(choices=[(0, 'home'), (1, 'mobile'), (2, 'work')], default=1, verbose_name='phone type'),
        ),
    ]
