# Generated by Django 2.2 on 2019-04-19 10:15

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='contact_box.Address'),
        ),
    ]
