# Generated by Django 2.2 on 2019-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0002_auto_20190419_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='person',
            field=models.ManyToManyField(to='contact_box.Person'),
        ),
    ]
