# Generated by Django 2.1.5 on 2019-02-06 19:29

import conference_rooms_reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(unique=True, validators=[conference_rooms_reservations.models.validate_date]),
        ),
    ]
