# Generated by Django 2.1.5 on 2019-03-29 09:43

import conference_rooms_reservations.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2019, 3, 29), validators=[conference_rooms_reservations.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
