# Generated by Django 2.2 on 2019-05-07 19:12

import conference_rooms_reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms_reservations', '0002_auto_20190425_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[conference_rooms_reservations.models.validate_date], verbose_name='reservation date'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='room capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='room name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='projector',
            field=models.BooleanField(blank=True, verbose_name='projector'),
        ),
    ]
