# Generated by Django 2.1.5 on 2019-04-01 14:59

import conference_rooms_reservations.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms_reservations', '0002_auto_20190329_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2019, 4, 1), validators=[conference_rooms_reservations.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_rooms_reservations.Room'),
        ),
    ]
