# Generated by Django 2.1.5 on 2019-04-04 13:13

import conference_rooms_reservations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms_reservations', '0003_auto_20190401_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(validators=[conference_rooms_reservations.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conference_rooms_reservations.Room'),
        ),
    ]
